# Generated by Django 2.2.12 on 2020-05-23 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_auto_20200523_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, help_text='Email of Receiver', max_length=254),
            preserve_default=False,
        ),
    ]
